### ISSUE TITLE
[1.15.2] Crashing on multiplayer servers

### ISSUE THREAD

**Issue by TheSorton** [yuitakaa/InvTweaksRenewed#1] opened 2020-06-07 19:37 UTC
Game crashes when middle clicking with it installed locally, but not on the server.

 Launcher gives:
```
The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: mouseClicked event handler
```
Full crash report minus system info can be found [here](https://hastebin.com/kuyawecigi.php).

**Comment by yuitakaa** [comment] 2020-06-08 05:30
I will look into it, but could you please try it without Optifine?

**Comment by 23SRLITheGamer** [comment] 2020-06-09 16:38
I have the same issue, but with keypressed event handler, I binded the sort to keys, and no Optifine installed.

**Comment by reo-ar** [comment] 2020-06-13 09:47
Please try the updated file in Curseforge.
And please give me the full latest.log if it crashes again, as those are generic errors and I need the full stacktrace

**Comment by 23SRLITheGamer** [comment] 2020-06-13 18:17
https://pastebin.com/RziMAbrx - Crash Report
https://pastebin.com/h0WFuRmk - latest.log

I'll try to send one without other mods that I have on, if needed.

**Comment by reo-ar** [comment] 2020-06-19 10:16
Please do try the new version without additional mods as I'm unreliably unable to reproduce this issue, I highly suspect FPSReducer might be at fault here. However I've also seen the crash in Paper-based servers.

**Comment by xyifer12** [comment] 2020-06-21 22:00
I am having this issue without any other mods while connected to a Paper server. I crash within 3 sort button clicks 100% of the time.

https://pastebin.com/TuAexzcF - Crash
https://pastebin.com/a66wAqgj - Latest.log

**Comment by reo-ar** [comment] 2020-06-26 07:09
I cannot recreate this under a minimal environment of this mod and 1.15.2 anymore, but please reopen this if the problem persists, the updated file will be posted in Curseforge.

**Comment by xyifer12** [comment] 2020-06-26 13:35
The issue persists. I have made progress narrowing down a cause. Adding an enchanted item to my inventory causes a crash when sorting.

![2020-06-26_08 31 53](https://user-images.githubusercontent.com/33806276/85862807-e04f9000-b787-11ea-8260-95717943f9b5.png)

[crash-2020-06-26_08.32.53-client.txt](https://github.com/yuitakaa/InvTweaksRenewed/files/4837198/crash-2020-06-26_08.32.53-client.txt)

[latest.log](https://github.com/yuitakaa/InvTweaksRenewed/files/4837201/latest.log)

**Comment by reo-ar** [comment] 2020-06-26 17:08
Please do note that render thread errors might appear when using Optifine as it's not fully compatible with Forge, but I'll try and recreate this issue later.

EDIT: Please try updating both Forge, Optiforge and Optifine, as I'm unable to recreate this issue anymore.

**Comment by reo-ar** [comment] 2020-06-29 04:08
Issue seems to be due to servers handling mouseclicked event differently rather than the mod's fault, closing.

**Closed by reo-ar** 2020-06-29 04:08 UTC
Labels: bug, paper
